### ISSUE TITLE
It is leaving files in local disc c and appdata! btw very good proect

### ISSUE THREAD

**Issue by praj3012** [fahmiyufrizal/minecraft-tlauncher-diskless#1]

**Comment by praj3012** [comment]
It is leaving files in local disc c and appdata

**Comment by fahmiyufrizal** [comment]
It's not actual files. It's junction point that needed by TLauncher configuration (at appdata) and minecraft app files (at C:\Minecraft). It will stimulate the folder that needed by TLauncher without copy all the files needed (it will cost some time and boring)

Btw, i choose C:\Minecraft because some diskless system have different drive letter between server and client.

Thanks for using my project!
